[[redirects]]
  from = "/signup.html"
  to = "/signup.html"
  status = 200
[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200
[[redirects]]
  from = "/admin-portal.html"
  to = "/admin-portal.html"
  status = 200
[[redirects]]
  from = "/customer-portal.html"
  to = "/customer-portal.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200